# Generated by Django 3.0.3 on 2020-03-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20200330_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='product',
            new_name='note',
        ),
    ]
