# Generated by Django 3.0.3 on 2020-04-20 21:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20200330_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
