# Generated by Django 3.0.3 on 2020-05-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(max_length=500),
        ),
    ]
