# Generated by Django 3.0.3 on 2020-05-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200530_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='orderno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
